name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
https://github.com/jamesbroadmore/carterscareportal/new/main?filename=.github%2Fworkflows%2Fdocker-image.yml&workflow_template=ci%2Fdocker-image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
